services:
  nest:
    container_name: api-eventify
    env_file:
      - .env
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db-eventify
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
