const diccionarioMensajes = {


    0: {statusHttp: 200, message: "Success"},
    1: {statusHttp: 201, message: "Successfully Created"},
    3: {statusHttp: 404, message: "Ocurrió un error al buscar el mail del usuario"},
    4: {statusHttp: 409, message: "Email existente"},
    5: {statusHttp: 500, message: "Error ocurrido durante la creación del usuario"},
    6: {statusHttp: 400, message: "Campos incompletos o datos inválidos"},
    7: {statusHttp: 401, message: "Error en la contraseña"},
    8: {statusHttp: 500, message: "Usuario o password no informados"},
    9: {statusHttp: 500, message: "Error ocurrido durante el paginado"},
    10: {statusHttp: 400, message: "ID de usuario requerido"},
    11: {statusHttp: 500, message: "Error ocurrido durante la búsqueda del usuario"},
    12: {statusHttp: 400, message: "Formato de email incorrecto"},
    13: {statusHttp: 500, message: "Error al conectarse con la base de datos"},
    14: {statusHttp: 400, message: "No se encontraron notificaciones"},
    15: {statusHttp: 400, message: "Campo de ID de notificacion faltante"},
    16: {statusHttp: 400, message: "ID de clase requerido"},
    17: {statusHttp: 404, message: "ID inexistente"}, 
    18: {statusHttp: 403, message: "El profesor no corresponde a la clase"}, 
    19: {statusHttp: 409, message: "La clase ha sido eliminada"}, 
    20: {statusHttp: 409, message: "Aún existen contrataciones en estado Aceptada o Solicitada para esta clase"}, 
    21: {statusHttp: 400, message: "ID y nuevo estado son datos requeridos"}, 
    22: {statusHttp: 400, message: "Los estados posibles de las clases son: 'Publicada' u 'Oculta'"}, 
    23: {statusHttp: 404, message: "Contratación no existente o en estado inválido."}, 
    24: {statusHttp: 403, message: "La contratación no corresponde al alumno logueado."}, 
    25: {statusHttp: 400, message: "Ya ha realizado un comentario para esta clase"}, 
    26: {statusHttp: 400, message: "Los estados posibles para el comentario son: Aceptado o Bloqueado"}, 
    27: {statusHttp: 403, message: "El comentario no corresponde al profesor"}, 
    28: {statusHttp: 409, message: "El comentario ya fue Aceptado o Bloqueado"}, 
    29: {statusHttp: 400, message: "Debe ingresar un motivo de bloqueo"}, 
    30: {statusHttp: 400, message: "Filtro de estado inválido"}, 
    31: {statusHttp: 404, message: "Clase no existente o no publicada."},
    32: {statusHttp: 409, message: "Ya posee una contratación para esta clase"},
    33: {statusHttp: 400, message: "Los estados posibles son: Aceptada, Finalizada o Cancelada"},
    34: {statusHttp: 403, message: "El usuario no esta asignado al contrato"},
    35: {statusHttp: 400, message: "El estado previo no es Solicitada o el usuario no es un Profesor"},
    36: {statusHttp: 400, message: "Solo se puede pasar a estado Cancelada si el estado previo es Solicitada"},
    37: {statusHttp: 400, message: "Solo se puede pasar a estado Finalizada si el estado previo es Aceptada"},
    38: {statusHttp: 500, message: "La calificación no se pudo convertir a entero"},
    39: {statusHttp: 400, message: "La calificación debe ser un numero entre 1 y 5"},
    40: {statusHttp: 409, message: "No es posible calificar una contratación en estado Solicitada o Cancelada"},
    
}

module.exports = diccionarioMensajes;